### ISSUE TITLE
Добавить шаг выгрузки из формата EDT 

### ISSUE THREAD

**Issue by goodwinvu** [firstBitSemenovskaya/jenkins-lib#18]
Если разработка ведётся без хранилища, неплохо было бы добавить возможность  сперва запускать шаги валидации ЕДТ и выгружзки ring'ом из исходников в формат EDT, а затем уже запускать шаги подготовки иб из файлов.

**Comment by nixel2007** [comment]
Наверное имеется ввиду все же конвертация ring'ом в формат конфигуратора, да? Или загрузка/создание базы из воркспейса.

Да, это в планах вместе с поддержкой загрузки конфигурации из исходников в формате конфигуратора

**Comment by nixel2007** [comment]
Или речь как раз про исходники в формате конфигурира, из которых нужно собрать цф и иб?

В любом случае, и то и то в планах :)
