### ISSUE TITLE
Как работать с расширениями?

### ISSUE THREAD

**Issue by goodwinvu** [firstBitSemenovskaya/jenkins-lib#56]
Дано:
Конфигурация в формате ЕДТ, лежит в репозитории гитлаба. С основной конфигурацией пайплайн работает, исходники собираются , проверочки работают, всё ок.
Встал вопрос - можно ли как-то реализовать также сборку расширений (расширения лежат в том же репе, рядом, по другому пути только) перед инициализацией базы ?

**Comment by nixel2007** [comment]
Думаю, тут подойдет настройка `initInfobase`->`additionalMigrationSteps`. В ней можно указать команды запуска vrunner (например, compileext/loadext или даже run для установки расширения в интерактивном режиме), с помощью которых и подгрузить нужные расширения в базу. дополнительные шаги миграции выполняются после создания ИБ и запуска миграции БСП (если она была включена), но до архивации ИБ и запуска блока с проверками.

**Comment by goodwinvu** [comment]
понял, буду пробовать
спасибо

**Comment by nixel2007** [comment]
вот только если расширения тоже в формате едт, то может возникнуть проблемка...

**Comment by goodwinvu** [comment]
разумеется - в формате ЕДТ  ))

**Comment by nixel2007** [comment]
Да, про полноценную поддержку расширений надо будет ещё подумать.
А в вашем случае, боюсь, надо будет немножечко подменить код вот тут:

https://github.com/firstBitSemenovskaya/jenkins-lib/blob/bbefb410b8a22f40117f3d98980433dfaef018b3/src/ru/pulsar/jenkins/library/steps/InitInfobase.groovy#L57

Убрать из строки использование переменной vrunnerPath, оставив там только it.

Тогда в additionalMigrationSteps можно будет указать команду запуска ring с параметрами

**Comment by goodwinvu** [comment]
супер, спасибо)
буду пробовать

**Comment by goodwinvu** [comment]
вобщем в форке поизгалялся
вроде все завелось и работает, но жутко костыльно выглядит и не ООП ни разу

**Comment by nixel2007** [comment]
я обязательно вернусь к этой задаче :)
