### ISSUE TITLE
Использование docker образов в сборочной линии

### ISSUE THREAD

**Issue by thedemoncat** [firstBitSemenovskaya/jenkins-lib#6]
@nixel2007 у меня тут https://git.oskk.1solution.ru/docker-images куча готовых образов, Можеть прикрутить их к сборке? Исходники я в ближайшее время начну публиковать в открытый доступ. Единственный момент по образам с 1С, публично не могу, но у меня есть приватный docker-registry

**Comment by nixel2007** [comment]
Привет.

Все шаги пайплайна сейчас у меня сейчас гоняются в докере. докер образы собираются на базе форка onec-docker от jugatsu.

https://github.com/firstBitSemenovskaya/onec-docker/blob/feature/first-bit/Layers.md
